ui <- fluidPage(titlePanel("Key to UK Phoridae Genera", windowTitle = "UK Phoridae Key"),
                tabsetPanel(
                  tabPanel("Abdomen", 
                           radioButtons("sternites", "Are segments 1 to 6 missing sternites?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("segment_3", "Which description best fits the papillae on segment 3?", choices = c("Small, oval-to-round papillae on each side towards the front margin", "Present but does not fit the description above", "Absent"), selected = character(0)),
                           radioButtons("segment_4_to_6", "Are there tergites on segments 4 to 6?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("segment_5", "Does segment have a complex gland opening?", choices = c("Yes", "No"), selected = character(0))
                  ),
                  tabPanel("Head",
                           radioButtons("arista", "Is the arista inserted apically?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("frons_bristles", "Are there conspicuous bristles between the anterior ocellus and the base of the antennae?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("frons_furrow", "Is there a median furrow extending outside the region of the supra-antennal bristles", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("palp_bristle", "Is the longest bristle on the palps more robust than the upper occipital?", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Legs",
                           radioButtons("hind_tibia_hair", "Which option best describes the hair on the dorsal face of the hind tibiae?", choices = c("Simply haired",
                                                                                                                                                 "1 dorsal hair palisade",
                                                                                                                                                 "2 to 3 dorsal hair palisades",
                                                                                                                                                 "Transverse combs of stoutish hairs"), selected = character(0)),
                           radioButtons("hind_tibia_bristles", "Which option best describes the bristles on the hind tibiae?", choices = c("A row of bristle-like hairs on either side of the hair palisade",
                                                                                                                                           "A row of bristle-like hairs behind the hair palisade",
                                                                                                                                           "At least 2 true-dorsal bristles and one antero-dorsal bristle near the upper true-dorsal bristle",
                                                                                                                                           "2 antero-dorsal bristles only, one situated near end of of upper thrid and one near the middle",
                                                                                                                                           "Isolated bristles",
                                                                                                                                           "Only apical bristles"), selected = character(0)),
                           radioButtons("mid_tibia_dorsal_bristles", "How many true-dorsal bristals are on the mid tibia?", choices = c("0 or 1", "2 or more"), selected = character(0)),
                           radioButtons("mid_tibia_anterior_bristles", "Which option best describes the forward facing bristle on the mid tibiae?", choices = c("Clearly longer than the width of the tibia at point of insertion",
                                                                                                                                                                "Shorter than the width of the tibia at the point of insertion",
                                                                                                                                                                "Absent"), selected = character(0)),
                           radioButtons("fore_tibia_bristles", "Is there a bristle in the upper two thirds of the fore tibia that is longer than the width of the tibia at its widest point, with a row of short, robust spines just below this?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("fore_tarsi", "Is there a clearly differentiated, short, dorsal, apical spur?", choices = c("Yes", "No"), selected = character(0)),
                           radioButtons("fore_metatarsus", "Is the fore metatarsus clearly longer than the fifth tarsal segment?", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Thorax",
                           radioButtons("mesopleural_hair", "Which option best describes the mesopleuron?", choices = c("Bare", 
                                                                                                                        "With some hairs on upper part",
                                                                                                                        "With a patch of fine hairs near dorsal edge",
                                                                                                                        "With hairs and a single long bristle near the posterior margin"), selected = character(0)),
                           radioButtons("mesopleural_furrow", "Is the mesopleural furrow present and centrally placed", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Wings", fluid = TRUE,
                    radioButtons("wing_membrane", "What colour is the wing membrane?", choices = c("Conspicuously darkened", "Strongly greyish or brownish", "Slightly greyish", "Clear"), selected = character(0)),
                    radioButtons("costa", "Does the costa thicken somewhat distally?", choices = c("Yes", "No"), selected = character(0)),
                    radioButtons("costal_cilia", "Are the costal cilia clearly longer than vein 2?", choices = c("Yes", "No"), selected = character(0)),
                    radioButtons("vein_sc", "Does vein Sc end before meeting vein 1?", choices = c("Yes", "No"), selected = character(0)),
                    radioButtons("vein_3_fork", "Is vein 3 forked?", choices = c("Yes" = "Forked", "No" = "Unforked (vein 2 is absent)"), selected = character(0)),
                    radioButtons("vein_3_hairs", "Which of these best describes the hairs on vein 3", choices = c("Single hair at base on the dorsal face",
                                                                                                                  "Between 0 and 3 hairs restricted to basal quarter", 
                                                                                                                  "3 to 5 hairs extending from the base along the dorsal face",
                                                                                                                  "A bristle like hair at base and 1-4 finer hairs before the fork",
                                                                                                                  "Between 5 and 10 hairs on dorsal face (may be quite fine)",
                                                                                                                  "Over 10 hairs on the dorsal face"), selected = character(0)),
                    radioButtons("vein_3_end", "Does vein 3 end in a small clear vesicle just beyond the point where it meets the costa?", choices = c("Yes", "No"), selected = character(0)),
                    radioButtons("vein_4", "Is the base of vein 4 obliterated?", choices = c("Yes", "No"), selected = character(0)),
                    radioButtons("vein_6", "Is there a sudden bend in the middle of vein 6, opposite and opposed to the basal curve of vein 5?", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Males", 
                           radioButtons("vein_6", "Is the third segment of the antennae drawn out into an elongated neck?", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Females", 
                           radioButtons("ovipositor", "Does the ovipositor curve downwards to a point?", choices = c("Yes", "No"), selected = character(0))),
                  tabPanel("Wingless females", "Wings")
                ),
                mainPanel(dataTableOutput("results")))
