name: R

on:
  workflow_dispatch:
  push:

jobs:
 
   create-shiny-r-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          packages: |
            any::tidyverse 
            any::shinylive
            any::httpuv

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create UI script
        run: Rscript -e 'source("build/create_ui.R")'

      - name: Create server script
        run: Rscript -e 'source("build/create_server.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add shiny/ui.R
          git add shiny/server.R
          git commit -am 'Shiny updated via github push' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
          
      - name: Create web app
        run: Rscript -e 'source("build/create_docs.R")'
        
      - name: Commit website
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am 'Website updated via github push' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
